### ISSUE TITLE
undefined method `content_tag' for Spree:Module

### ISSUE THREAD

**Issue by fredguth** [tiagoamaro/spree_cpf#2] opened 2014-01-06 19:49 UTC
Followed the instructions, but the following error occurred when in checkout:

 Showing /Users/fredguth/.rvm/gems/ruby-2.1.0/gems/spree_frontend-2.1.3/app/views/spree/address/_form.html.erb where line #14 raised:

undefined method `content_tag' for Spree:Module

**Comment by tiagoamaro** [comment] 2014-01-07 01:28
Hi @fredguth,

I could not reproduce this error. Could you give me more information about your Gemfile?

I see that you are using spree 2.1.3 and ruby 2.1.0, so I ran a test with `ruby 2.1.0` and `spree 2.1.3` and still got no errors.

Here is a sample of my `Gemfile`:

```
...
gem 'spree', '2.1.3'
gem 'spree_cpf', '2.1.2'
gem 'spree_auth_devise', :git => 'https://github.com/spree/spree_auth_devise.git', :branch => '2-1-stable'
```

Edit: I updated the gem version to match the current spree stable version (2.1.3). Please use the [Rubygems version of this extension](https://rubygems.org/gems/spree_cpf).

**Comment by fredguth** [comment] 2014-01-07 13:27
Now it is working. Just noticed that when you put an invalid CPF this error happens:

1 error prohibited this record from being saved:

There were problems with the following fields:

```
Bill address translation missing: en.activerecord.errors.models.spree/order.attributes.bill_address.cpf_invalid
```

**Comment by tiagoamaro** [comment] 2014-01-07 13:31
Great @fredguth. I didn't notice this missing I18n error. Could you make a pull request this translation?

**Comment by tiagoamaro** [comment] 2014-01-19 00:21
@fredguth , I fixed the translation error you mentioned. With the sample `en.yml` file, you should successfully create a `pt-BR.yml` file. Good Luck.

I'm going to close this issue for now. If you have other problems, please, open another issue.

**Closed as completed** 2014-01-19 00:23 UTC

**Comment by fredguth** [comment] 2014-01-19 03:00
Thanks
